# Auto-generated using compose2nix v0.3.1.
{ config, pkgs, lib, ... }:

{
  sops.secrets."qbittorrent" = {};

  networking = {
    firewall = {
      allowedTCPPorts = [ 8082 ];
    };
  };
  # Containers
  virtualisation.oci-containers.containers."qbittorrent" = {
    image = "lscr.io/linuxserver/qbittorrent:latest";
    environment = {
      "TZ" = "\"America/New York\"";
      "WEBUI_PORT" = "8082";
      "PGID" = "333";
      "PUID" = "333";
    };
    volumes = [
      "/home/pixls/qBittorrent:/config:rw"
      "/ortus:/snack-share:rw"
    ];
    dependsOn = [
      "gluetun"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=container:gluetun"
    ];
  };
  systemd.services."podman-qbittorrent" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-qbittorrent-root.target"
    ];
    wantedBy = [
      "podman-compose-qbittorrent-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-qbittorrent-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
